name: Anylinux-AppImage
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true
on:
  schedule:
    - cron: "0 7 1/21 * *" # We default to rebuilding every 21 days, change this to your liking
  workflow_dispatch: {}

jobs:
  build:
    name: "${{ matrix.name }} (${{ matrix.arch }})"
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        include:
          - runs-on: ubuntu-latest
            name: Build AppImage
            arch: x86_64
          # comment out these 3 lines if aarch64 is not wanted
          #- runs-on: ubuntu-24.04-arm
          #  name: Build AppImage
          #  arch: aarch64
    container: ghcr.io/pkgforge-dev/archlinux:latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Preparing Container
        uses: sarrchri/anylinux-setup-action@5852f83bff65780bd65d03d80283b80ba4ebd6d4
      - name: Install Dependencies
        run: /bin/sh ./get-dependencies.sh
      - name: Make AppImage
        run: /bin/sh ./make-appimage.sh
      - name: Upload artifact
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: AppImage-${{ matrix.arch }}
          path: dist

  release:
    if: ${{ github.ref_name == 'main' }}
    needs: [build]
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          pattern: AppImage-*
          merge-multiple: true
      - name: Release AppImage
        uses: pkgforge-dev/make-stable-appimage-release@4ed3d48ccb065352b6e6c0db6d39885b201c54a0 #v1.1
